import type { EditScope, ElementMetrics, InspectorTab, VisualChange, VisualCheckpoint } from './types';
type InspectorProps = {
    tab: InspectorTab;
    onTabChange: (tab: InspectorTab) => void;
    selected: HTMLElement | null;
    metrics: ElementMetrics | null;
    changes: VisualChange[];
    checkpoints: VisualCheckpoint[];
    copied: boolean;
    note: string;
    editScope: EditScope;
    onEditScope: (scope: EditScope) => void;
    onResetScope: () => void;
    aspectLocked: boolean;
    onAspectLocked: (locked: boolean) => void;
    onStyle: (property: string, value: string) => void;
    onStyleAsset: (property: string, runtimeValue: string, displayValue: string) => void;
    onAttribute: (attribute: string, runtimeValue: string, displayValue?: string) => void;
    onTranslate: (x: number, y: number) => void;
    onAlign: (axis: 'horizontal' | 'vertical', alignment: 'start' | 'center' | 'end') => void;
    onResize: (dimension: 'width' | 'height', value: string) => void;
    onNudge: (x: number, y: number) => void;
    onScale: (factor: number) => void;
    onFitParent: () => void;
    onCopy: () => void;
    onResetSelected: () => void;
    onClear: () => void;
    onRevertChange: (change: VisualChange) => void;
    onSaveCheckpoint: (name: string) => void;
    onRestoreCheckpoint: (checkpoint: VisualCheckpoint) => void;
    onDeleteCheckpoint: (id: string) => void;
    onNoteChange: (note: string) => void;
    onEditText: () => void;
    canEditText: boolean;
    onMoveSibling: (direction: 1 | -1) => void;
    onMoveToParent: (parent: HTMLElement) => void;
    onSelectRelative: (direction: 'parent' | 'previous' | 'next' | 'child') => void;
    onDuplicate: () => void;
    onRemove: () => void;
    canRestructure: boolean;
};
export declare function Inspector({ tab, onTabChange, selected, metrics, changes, checkpoints, copied, note, editScope, onEditScope, onResetScope, aspectLocked, onAspectLocked, onStyle, onStyleAsset, onAttribute, onTranslate, onAlign, onResize, onNudge, onScale, onFitParent, onCopy, onResetSelected, onClear, onRevertChange, onSaveCheckpoint, onRestoreCheckpoint, onDeleteCheckpoint, onNoteChange, onEditText, canEditText, onMoveSibling, onMoveToParent, onSelectRelative, onDuplicate, onRemove, canRestructure }: InspectorProps): import("react").JSX.Element;
export {};
