import type { EditScope, ResponsiveDevice } from './types';
import type { DataBindingTarget, NamedStyle, PortableSection, RepeaterDefinition } from './studio';
import type { RulerGuide, RulerUnit } from './CanvasRulers';
type MakeCodeState = {
    status: 'idle' | 'checking' | 'ready' | 'saving' | 'saved' | 'error';
    message?: string;
    file?: string;
};
type StudioPanelProps = {
    selected: HTMLElement | null;
    selectedCount: number;
    grouped: boolean;
    editScope: EditScope;
    responsiveOverrides: Record<string, Set<string>>;
    gridVisible: boolean;
    rulersVisible: boolean;
    rulerUnit: RulerUnit;
    rulerGuides: RulerGuide[];
    snappingEnabled: boolean;
    snapToGrid: boolean;
    gridSize: number;
    sections: PortableSection[];
    namedStyles: NamedStyle[];
    activeRepeater: RepeaterDefinition | null;
    makeCodeState: MakeCodeState;
    changeCount: number;
    onClose: () => void;
    onGridVisible: (visible: boolean) => void;
    onRulersVisible: (visible: boolean) => void;
    onRulerUnit: (unit: RulerUnit) => void;
    onRulerGuidesChange: (guides: RulerGuide[]) => void;
    onSnappingEnabled: (enabled: boolean) => void;
    onSnapToGrid: (enabled: boolean) => void;
    onGridSize: (size: number) => void;
    onAlignSelection: (axis: 'horizontal' | 'vertical', alignment: 'start' | 'center' | 'end') => void;
    onDistributeSelection: (axis: 'horizontal' | 'vertical') => void;
    onGroupSelection: () => void;
    onUngroupSelection: () => void;
    onResetResponsiveProperty: (device: ResponsiveDevice, property: string) => void;
    onSaveSection: (name: string) => void;
    onInsertSection: (section: PortableSection) => void;
    onCopySection: (section: PortableSection) => void;
    onImportSection: () => void;
    onDeleteSection: (id: string) => void;
    onCreateNamedStyle: (name: string) => void;
    onApplyNamedStyle: (style: NamedStyle) => void;
    onUpdateNamedStyle: (style: NamedStyle) => void;
    onDeleteNamedStyle: (id: string) => void;
    onCreateRepeater: (name: string, data: Array<Record<string, unknown>>) => void;
    onBindRepeater: (field: string, target: DataBindingTarget) => void;
    onUpdateRepeaterData: (data: Array<Record<string, unknown>>) => void;
    onRenderRepeater: () => void;
    onDeleteRepeater: () => void;
    onMakeItCode: () => void;
};
export declare function StudioPanel(props: StudioPanelProps): import("react").JSX.Element;
export type { MakeCodeState };
