export type InspectorTab = 'design' | 'changes';
export type ResponsiveDevice = 'desktop' | 'tablet' | 'phone';
export type EditScope = 'all' | ResponsiveDevice;
export type VisualChangeKind = 'style' | 'responsive-style' | 'text' | 'attribute' | 'insert' | 'remove' | 'reorder';
export type VisualChange = {
    id: string;
    selector: string;
    previousSelector?: string;
    label: string;
    property: string;
    previousValue: string;
    value: string;
    runtimeValue?: string;
    previousRuntimeValue?: string;
    timestamp: number;
    kind: VisualChangeKind;
    parentSelector?: string;
    previousParentSelector?: string;
    index?: number;
    previousIndex?: number;
    html?: string;
    device?: ResponsiveDevice;
    groupId?: string;
    stableId?: string;
};
export type VisualCheckpoint = {
    id: string;
    name: string;
    timestamp: number;
    changes: VisualChange[];
    note: string;
};
export type ElementMetrics = {
    x: number;
    y: number;
    translateX: number;
    translateY: number;
    width: number;
    height: number;
    marginTop: number;
    marginRight: number;
    marginBottom: number;
    marginLeft: number;
    paddingTop: number;
    paddingRight: number;
    paddingBottom: number;
    paddingLeft: number;
    fontSize: number;
    fontFamily: string;
    fontWeight: string;
    letterSpacing: number;
    lineHeight: number;
    color: string;
    backgroundColor: string;
    backgroundImage: string;
    backgroundSize: string;
    backgroundPosition: string;
    backgroundRepeat: string;
    borderRadius: number;
    borderWidth: number;
    borderStyle: string;
    borderColor: string;
    boxShadow: string;
    opacity: number;
    textAlign: string;
    objectFit: string;
    objectPosition: string;
    display: string;
    flexDirection: string;
    justifyContent: string;
    alignItems: string;
    gap: number;
    gridTemplateColumns: string;
};
